version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: ServerNest
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_db
    depends_on:
      - db
    networks:
      - db-network

  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - db-network

volumes:
  postgres_data:

networks:
  db-network:
    driver: bridge
